import type { Animal, User, Application, Appointment, AdoptionRecord } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    password: 'password123',
    role: 'ADOPTER',
    phone: '(555) 234-5678',
    address: '123 Maple Street, Springfield, IL 62701',
  },
  {
    id: 'u2',
    name: 'Admin User',
    email: 'admin@pawconnect.edu',
    password: 'admin123',
    role: 'ADMIN',
    phone: '(555) 000-0001',
    address: 'PawConnect Animal Shelter, Campus Drive',
  },
];

export const INITIAL_ANIMALS: Animal[] = [
  {
    id: 'a1',
    name: 'Buddy',
    type: 'DOG',
    breed: 'Golden Retriever',
    age: '2 years',
    gender: 'Male',
    status: 'AVAILABLE',
    photo: 'https://images.unsplash.com/photo-1583786693544-e352f898888d?w=600&h=450&fit=crop&auto=format',
    description:
      'Buddy is a playful and affectionate Golden Retriever who loves to fetch and cuddle. He is great with kids, calm with strangers, and an absolute joy to be around. He knows basic commands and is house-trained.',
    weight: '65 lbs',
    color: 'Golden',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Healthy and up-to-date on all vaccines. Heartworm negative. Dental health excellent.',
    arrivalDate: '2026-07-15',
    intakeReason: 'Owner surrender',
    medicalRecords: [
      { id: 'mr1', date: '2026-07-15', type: 'Intake Exam', description: 'Full physical exam on arrival. All clear. Coat and teeth in good condition.', vet: 'Dr. Emily Chen' },
      { id: 'mr2', date: '2026-07-16', type: 'Vaccination', description: 'DHPP booster and Rabies vaccine administered. Bordetella given.', vet: 'Dr. Emily Chen' },
      { id: 'mr3', date: '2026-08-01', type: 'Heartworm Test', description: 'Heartworm test negative. Started on monthly preventive (Heartgard).', vet: 'Dr. James Park' },
      { id: 'mr4', date: '2026-09-01', type: 'Wellness Check', description: 'Monthly wellness check. Weight stable at 65 lbs. Excellent condition.', vet: 'Dr. Emily Chen' },
    ],
  },
  {
    id: 'a2',
    name: 'Luna',
    type: 'CAT',
    breed: 'Domestic Shorthair',
    age: '1 year',
    gender: 'Female',
    status: 'AVAILABLE',
    photo: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=600&h=450&fit=crop&auto=format',
    description:
      'Luna is a curious and gentle tabby who loves to explore and cuddle in the evenings. She is litter-trained, good with calm households, and will often greet you at the door.',
    weight: '8 lbs',
    color: 'Brown tabby',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Excellent health. FVRCP and Rabies current. Spayed. Healthy weight.',
    arrivalDate: '2026-08-01',
    intakeReason: 'Found stray',
    medicalRecords: [
      { id: 'mr5', date: '2026-08-01', type: 'Intake Exam', description: 'Stray intake. Minor ear mites treated with Tresaderm. Otherwise healthy.', vet: 'Dr. Emily Chen' },
      { id: 'mr6', date: '2026-08-05', type: 'Spay Surgery', description: 'Routine spay surgery performed. Recovered smoothly with no complications.', vet: 'Dr. Maria Santos' },
      { id: 'mr7', date: '2026-08-10', type: 'Vaccination', description: 'FVRCP booster and Rabies vaccine administered. FeLV/FIV test negative.', vet: 'Dr. Emily Chen' },
    ],
  },
  {
    id: 'a3',
    name: 'Max',
    type: 'DOG',
    breed: 'Labrador Mix',
    age: '3 years',
    gender: 'Male',
    status: 'APPLICATION_PENDING',
    photo: 'https://images.unsplash.com/photo-1604606363386-dd3f2357ad87?w=600&h=450&fit=crop&auto=format',
    description:
      'Max is an energetic and loyal Labrador mix who loves outdoor adventures, swimming, and playing fetch. He needs an active family with a yard and would do best without young children.',
    weight: '72 lbs',
    color: 'Brown and white',
    vaccinated: true,
    neutered: true,
    microchipped: false,
    healthSummary: 'Healthy. Mild hip dysplasia monitored annually. All vaccines current. Flea prevention monthly.',
    arrivalDate: '2026-06-20',
    intakeReason: 'Owner surrender',
    medicalRecords: [
      { id: 'mr8', date: '2026-06-20', type: 'Intake Exam', description: 'Physical exam performed. Mild hip dysplasia noted during palpation.', vet: 'Dr. James Park' },
      { id: 'mr9', date: '2026-06-22', type: 'X-Ray', description: 'Hip X-rays taken. Mild bilateral dysplasia confirmed. No immediate treatment needed; annual monitoring recommended.', vet: 'Dr. James Park' },
      { id: 'mr10', date: '2026-07-01', type: 'Vaccination', description: 'DHPP and Rabies boosters given.', vet: 'Dr. James Park' },
    ],
  },
  {
    id: 'a4',
    name: 'Mochi',
    type: 'CAT',
    breed: 'Tabby',
    age: '6 months',
    gender: 'Female',
    status: 'AVAILABLE',
    photo: 'https://images.unsplash.com/photo-1583524505974-6facd53f4597?w=600&h=450&fit=crop&auto=format',
    description:
      'Mochi is an adorable cream tabby kitten with big bright eyes and endless energy. She loves to play with toy mice, climb cat trees, and would thrive with another cat companion.',
    weight: '4 lbs',
    color: 'Cream tabby',
    vaccinated: true,
    neutered: false,
    microchipped: true,
    healthSummary: 'Healthy kitten. First FVRCP series complete. Spay surgery scheduled for October.',
    arrivalDate: '2026-08-15',
    intakeReason: 'Surrendered litter',
    medicalRecords: [
      { id: 'mr11', date: '2026-08-15', type: 'Intake Exam', description: 'Healthy kitten intake from surrendered litter. All clear.', vet: 'Dr. Maria Santos' },
      { id: 'mr12', date: '2026-08-20', type: 'Vaccination', description: 'First FVRCP series started. Second dose scheduled at 10 weeks.', vet: 'Dr. Maria Santos' },
      { id: 'mr13', date: '2026-09-05', type: 'Vaccination', description: 'Second FVRCP dose given. Kitten growing well, weight 4 lbs.', vet: 'Dr. Maria Santos' },
    ],
  },
  {
    id: 'a5',
    name: 'Rocky',
    type: 'DOG',
    breed: 'American Pit Bull Terrier',
    age: '4 years',
    gender: 'Male',
    status: 'AVAILABLE',
    photo: 'https://images.unsplash.com/photo-1675701917667-d654fa82e536?w=600&h=450&fit=crop&auto=format',
    description:
      'Rocky may look tough but he has the gentlest soul. He loves belly rubs, long walks, and lounging on the couch. He is great with adults and does best as the only pet in the home.',
    weight: '58 lbs',
    color: 'Brindle',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Excellent health. All vaccines current. Negative for all vector-borne diseases. Weight restored to healthy range.',
    arrivalDate: '2026-05-10',
    intakeReason: 'Rescued from neglect situation',
    medicalRecords: [
      { id: 'mr14', date: '2026-05-10', type: 'Intake Exam', description: 'Underweight on arrival (48 lbs). Mild skin irritation. Started on high-nutrition diet.', vet: 'Dr. James Park' },
      { id: 'mr15', date: '2026-06-01', type: 'Follow-up', description: 'Weight improved to 58 lbs. Skin cleared. Excellent overall condition.', vet: 'Dr. James Park' },
      { id: 'mr16', date: '2026-07-01', type: 'Vaccination', description: 'DHPP, Rabies, and Bordetella boosters given. Flea/tick prevention applied.', vet: 'Dr. Emily Chen' },
    ],
  },
  {
    id: 'a6',
    name: 'Cleo',
    type: 'CAT',
    breed: 'Domestic Shorthair',
    age: '2 years',
    gender: 'Female',
    status: 'FOSTERED',
    photo: 'https://images.unsplash.com/photo-1558618047-f4b511aae74d?w=600&h=450&fit=crop&auto=format',
    description:
      'Cleo is a mysterious and elegant black cat currently in foster care recovering from an upper respiratory infection. She is warming up to people and will be a wonderful companion for a patient adopter.',
    weight: '9 lbs',
    color: 'Black',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Recovering well. URI resolved. All vaccines current. Spayed. Microchipped.',
    arrivalDate: '2026-07-01',
    intakeReason: 'Found stray',
    medicalRecords: [
      { id: 'mr17', date: '2026-07-01', type: 'Intake Exam', description: 'Upper respiratory infection on intake. Started on doxycycline.', vet: 'Dr. Emily Chen' },
      { id: 'mr18', date: '2026-07-15', type: 'Follow-up', description: 'URI fully resolved. Placed in foster care to continue socialization.', vet: 'Dr. Emily Chen' },
      { id: 'mr19', date: '2026-08-01', type: 'Vaccination', description: 'FVRCP booster and Rabies administered. FeLV/FIV negative.', vet: 'Dr. Emily Chen' },
    ],
  },
  {
    id: 'a7',
    name: 'Daisy',
    type: 'DOG',
    breed: 'Beagle',
    age: '5 years',
    gender: 'Female',
    status: 'APPROVED',
    photo: 'https://images.unsplash.com/photo-1594005374167-5fd900fb82c9?w=600&h=450&fit=crop&auto=format',
    description:
      'Daisy is a sweet and curious Beagle with an incredible nose for adventure. She has been approved for adoption and is patiently waiting to meet her new family. She loves trails, treats, and nap time.',
    weight: '25 lbs',
    color: 'Tri-color',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Excellent health. Dental cleaning done in May. All vaccines current. Healthy weight.',
    arrivalDate: '2026-04-15',
    intakeReason: 'Owner surrender',
    medicalRecords: [
      { id: 'mr20', date: '2026-04-15', type: 'Intake Exam', description: 'Good health on intake. Slightly overweight (28 lbs). Started on diet food.', vet: 'Dr. Maria Santos' },
      { id: 'mr21', date: '2026-05-20', type: 'Dental Cleaning', description: 'Full dental cleaning and polishing. No extractions needed. Weight down to 25 lbs.', vet: 'Dr. Maria Santos' },
      { id: 'mr22', date: '2026-06-15', type: 'Vaccination', description: 'DHPP, Rabies, and Leptospira boosters given.', vet: 'Dr. Maria Santos' },
    ],
  },
  {
    id: 'a8',
    name: 'Oliver',
    type: 'CAT',
    breed: 'Orange Tabby',
    age: '3 years',
    gender: 'Male',
    status: 'ADOPTED',
    photo: 'https://images.unsplash.com/photo-1620070687415-4c8e50a042fa?w=600&h=450&fit=crop&auto=format',
    description:
      'Oliver found his forever home and is living his best life with his new family! He loves sunny windowsills, string toys, and being the center of attention.',
    weight: '11 lbs',
    color: 'Orange',
    vaccinated: true,
    neutered: true,
    microchipped: true,
    healthSummary: 'Healthy and thriving in his forever home.',
    arrivalDate: '2026-01-10',
    intakeReason: 'Owner surrender',
    medicalRecords: [
      { id: 'mr23', date: '2026-01-10', type: 'Intake Exam', description: 'Good health on intake. Neutered and microchipped prior to arrival.', vet: 'Dr. Emily Chen' },
      { id: 'mr24', date: '2026-01-15', type: 'Vaccination', description: 'FVRCP booster and Rabies administered. FeLV/FIV negative.', vet: 'Dr. Emily Chen' },
    ],
  },
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app1',
    animalId: 'a1',
    adopterId: 'u1',
    adopterName: 'Sarah Johnson',
    adopterEmail: 'sarah@example.com',
    status: 'APPROVED',
    submittedDate: '2026-09-01',
    reviewedDate: '2026-09-03',
    reason: 'I have always dreamed of having a Golden Retriever. I have a large backyard and work from home, so Buddy would never be alone.',
    experience: 'I grew up with dogs and have been a responsible pet owner for over 10 years. My previous dog, Bailey, lived a long and happy life.',
    livingArrangement: 'House with large fenced yard',
    hasYard: true,
    hasOtherPets: false,
    otherPetsDescription: '',
    employmentStatus: 'Full-time remote software developer',
    references: 'Dr. Amy Williams (vet): (555) 111-2222; Mark Thompson (neighbor): (555) 333-4444',
    appointmentId: 'apt1',
  },
  {
    id: 'app2',
    animalId: 'a4',
    adopterId: 'u1',
    adopterName: 'Sarah Johnson',
    adopterEmail: 'sarah@example.com',
    status: 'PENDING',
    submittedDate: '2026-09-10',
    reason: 'Mochi is absolutely adorable and I think she would love my home. I have experience with kittens and know they need lots of enrichment.',
    experience: 'Had two cats growing up. Understand kitten behavior and needs.',
    livingArrangement: 'Apartment (cat-proofed)',
    hasYard: false,
    hasOtherPets: false,
    otherPetsDescription: '',
    employmentStatus: 'Full-time remote software developer',
    references: 'Dr. Amy Williams (vet): (555) 111-2222',
  },
  {
    id: 'app3',
    animalId: 'a3',
    adopterId: 'u3',
    adopterName: 'Michael Torres',
    adopterEmail: 'mtorres@example.com',
    status: 'PENDING',
    submittedDate: '2026-09-12',
    reason: 'Max looks like the perfect adventure companion for my active lifestyle.',
    experience: 'Owned Labs for 8 years. Comfortable with high-energy dogs.',
    livingArrangement: 'House with fenced yard',
    hasYard: true,
    hasOtherPets: false,
    otherPetsDescription: '',
    employmentStatus: 'Physical therapist',
    references: 'Jennifer Lee (friend): (555) 555-6666',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt1',
    applicationId: 'app1',
    animalId: 'a1',
    animalName: 'Buddy',
    adopterId: 'u1',
    adopterName: 'Sarah Johnson',
    date: '2026-09-25',
    time: '10:00 AM',
    status: 'SCHEDULED',
    notes: 'Meet and greet with Buddy. Please bring any existing pet health records and a valid ID.',
  },
];

export const INITIAL_ADOPTION_HISTORY: AdoptionRecord[] = [
  {
    id: 'adh1',
    animalId: 'a8',
    animalName: 'Oliver',
    animalType: 'CAT',
    animalBreed: 'Orange Tabby',
    animalPhoto: 'https://images.unsplash.com/photo-1620070687415-4c8e50a042fa?w=600&h=450&fit=crop&auto=format',
    adopterId: 'u1',
    adopterName: 'Sarah Johnson',
    adoptionDate: '2026-06-15',
    appointmentId: 'apt0',
  },
];
